"""Add chat models

Revision ID: 6df4b7f3e71d
Revises: 6c9d3a2b4f11
Create Date: 2026-04-29 15:58:20.534061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6df4b7f3e71d'
down_revision: Union[str, None] = '6c9d3a2b4f11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_rooms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_rooms_user_id'), 'chat_rooms', ['user_id'], unique=True)
    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('room_id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('content', sa.String(length=2000), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_room_id'), 'chat_messages', ['room_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_sender_id'), 'chat_messages', ['sender_id'], unique=False)
    op.drop_index('ix_basket_items_basket_id', table_name='basket_items')
    op.drop_index('ix_basket_items_product_id', table_name='basket_items')
    op.drop_index('ix_baskets_base_id', table_name='baskets')
    op.drop_index('ix_baskets_session_id', table_name='baskets')
    op.drop_index('ix_baskets_user_id', table_name='baskets')
    op.drop_index('ix_cart_items_basket_id', table_name='cart_items')
    op.drop_index('ix_cart_items_cart_id', table_name='cart_items')
    op.drop_index('ix_carts_session_id', table_name='carts')
    op.drop_index('ix_orders_payment_ref', table_name='orders')
    op.drop_index('ix_orders_user_id', table_name='orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_orders_user_id', 'orders', ['user_id'], unique=False)
    op.create_index('ix_orders_payment_ref', 'orders', ['payment_ref'], unique=False)
    op.create_index('ix_carts_session_id', 'carts', ['session_id'], unique=False)
    op.create_index('ix_cart_items_cart_id', 'cart_items', ['cart_id'], unique=False)
    op.create_index('ix_cart_items_basket_id', 'cart_items', ['basket_id'], unique=False)
    op.create_index('ix_baskets_user_id', 'baskets', ['user_id'], unique=False)
    op.create_index('ix_baskets_session_id', 'baskets', ['session_id'], unique=False)
    op.create_index('ix_baskets_base_id', 'baskets', ['base_id'], unique=False)
    op.create_index('ix_basket_items_product_id', 'basket_items', ['product_id'], unique=False)
    op.create_index('ix_basket_items_basket_id', 'basket_items', ['basket_id'], unique=False)
    op.drop_index(op.f('ix_chat_messages_sender_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_room_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_rooms_user_id'), table_name='chat_rooms')
    op.drop_table('chat_rooms')
    # ### end Alembic commands ###
